---
- name: Windows Change Hostname
  gather_facts: false
  hosts: windows
  tasks:
    - name: Change Name
      win_hostname:
        name: "{{ hostname }}"
      register: req

    - name: Reboot
      win_reboot:
      when: req.reboot_required