---
- name: Deploying customer
  hosts: windows
  tasks:

#read json
    - name: Read Json
      ansible.builtin.shell: cat /etc/ansible/customers.json
      register: result
      delegate_to: localhost

    - name: save json
      ansible.builtin.set_fact:
          jsondata: "{{ result.stdout | from_json }}"

    - name: Debug data
      ansible.builtin.debug:
        var: jsondata

#Create OU
    - name: Create OU
      community.windows.win_domain_ou:
        name: "{{ item.name }}"
        state: present
      loop: "{{ jsondata }}"

    - name: Execute Powershell
      ansible.windows.win_shell:
        Get-ADOrganizationalUnit -Filter * -SearchBase "DC=customers,DC=com"
      register: ou_output

    - name: Display OU
      ansible.builtin.debug:
        var: ou_output.stdout_lines

#CREATE AD
    - name: Craate AD
      community.windows.win_domain_user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        path: "ou={{ item.name }},DC=customers,DC=com"
      loop: "{{ jsondata }}"

    - name: Execute Powershell cmd
      ansible.windows.win_shell:
        Get-ADUser -Filter * -SearchBase "DC=customers,DC=com"
      register: ad_output

    - name: Display ADuser
      ansible.builtin.debug:
        var: ad_output.stdout_lines

#CREATE DNS
    - name: Gather IIS WEB
      ansible.builtin.set_fact:
        iis_server_ip: "{{ groups['iis'] | map('extract', hostvars, 'ansible_host') | list }}"

    - name: Display IIS
      ansible.builtin.debug:
        var: iis_server_ip

    - name: Create Database
      community.windows.win_dns_record:
        name: "{{ item.domain_prefix }}"
        type: "A"
        value: "{{ iis_server_ip | random }}"
        zone: "customers.com"
      loop: "{{ jsondata }}"

    - name: Execute Powershell cmd dns
      ansible.windows.win_shell:
        Get-DnsServerResourceRecord -ZoneName customers.com
      register: dns_records_output

    - name: Display ADuser dns
      ansible.builtin.debug:
        var: dns_records_output.stdout_lines

# IIS CONTENT
    - name: Create Folder Virtual Host
      ansible.builtin.win_file:
        path: "C:\\inetpub\\{{ item.domain_prefix }}"
        state: directory
      loop: "{{ jsondata }}"

    - name: Insert Path
      ansible.builtin.win_lineinfile:
        path: "C:\\inetpub\\{{ item.domain_prefix }}\\index.html"
        line: "{{ item.message }}"
        create: yes
      loop: "{{ jsondata }}"

    - name: Execute Powershell cmd to list Folder
      ansible.windows.win_shell:
        Get-ChildItem -Path C:\inetpub -Recurse
      register: dir_output

    - name: Display direc listing
      ansible.builtin.debug:
        var: dir_output.stdout_lines

    - name: IIS Site
      community.windows.win_iis_website:
        name: "{{ item.domain_prefix }}"
        state: started
        hostname: "{{ item.domain_prefix }}.customers.com"
        physical_path: "C:\\inetpub\\{{ item.domain_prefix }}"
      loop: "{{ jsondata }}"