---
- name: Configure DNS Server
  hosts: dns
  tasks:
    - name: Install Bind9
      apt:
        name: bind9
        state: present

    #FORWARD DNS
    - name: Configure named DNS Master
      ansible.builtin.template:
        src: /data/ansible/linux/2-dns-server/named.conf.local.master
        dest: /etc/bind/named.conf.local
      when: inventory_hostname == groups['dns'][0]

    - name: Copy
      ansible.builtin.command:
        cp /etc/bind/db.local /etc/bind/db.lksn2023.com
      when: inventory_hostname == groups['dns'][0]

    - name: Replace
      ansible.builtin.replace:
        path: /etc/bind/db.lksn2023.com
        regexp: 'localhost'
        replace: 'lksn2023.com'
      when: inventory_hostname == groups['dns'][0]

    - name: Replace reverse
      ansible.builtin.replace:
        path: /etc/bind/db.lksn2023.com
        regexp: '127.0.0.1'
        replace: '{{ ansible_host }}'
      when: inventory_hostname == groups['dns'][0]

    - name: Create A Record
      ansible.builtin.lineinfile:
        path: /etc/bind/db.lksn2023.com
        line: |
          {% for host in groups['linux'] %}
          {{ host }} IN A {{ hostvars[host].ansible_host }}
          {% endfor %}
          intranet  IN  A 10.22.0.51
      when: inventory_hostname == groups['dns'][0]

# END FORWARD DNS

#REVERSE DNS
    - name: Copy DB.0
      ansible.builtin.command:
        cp /etc/bind/db.0 /etc/bind/db.reverse.lksn2023.com
      when: inventory_hostname == groups['dns'][0]

    - name: Replace db.reverse.lksn.com
      ansible.builtin.replace:
        path: /etc/bind/db.reverse.lksn2023.com
        regexp: 'localhost'
        replace: 'lksn2023.com'
      when: inventory_hostname == groups['dns'][0]

    - name: Create PTR Record
      ansible.builtin.lineinfile:
        path: /etc/bind/db.reverse.lksn2023.com
        line: |
          1  IN  PTR LIN1.lksn2023.com.
          2  IN  PTR LIN2.lksn2023.com.
          3  IN  PTR LIN3.lksn2023.com.
          4  IN  PTR LIN4.lksn2023.com.
          51  IN  PTR intranet.lksn2023.com.
      when: inventory_hostname == groups['dns'][0]

#END REVERSE
# DNS SLAVE
    - name: Configure named DNS slave
      ansible.builtin.template:
        src: /data/ansible/linux/2-dns-server/named.conf.local.slave
        dest: /etc/bind/named.conf.local
      when: inventory_hostname != groups['dns'][0]
      
#END DNS SLAVE
    - name: Restart bind
      service:
        name: bind9
        state: restarted