---
- name: Configure high available
  hosts: ha
  vars:
    floating_ip: 10.22.0.51
  tasks:
    - name: Install Keepalived
      ansible.builtin.apt:
        name: keepalived
        state: present

    - name: Copy Keepalived
      ansible.builtin.template:
        src: /data/ansible/linux/5-ha-intranet/keepalived.conf
        dest: /etc/keepalived/keepalived.conf

    - name: Restart Keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted

#HAPROXY
    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present

    - name: Clean file haproxy
      ansible.builtin.shell:
        echo -n "" > /etc/haproxy/haproxy.cfg

    - name: Copy haproxy
      ansible.builtin.lineinfile:
        path: /etc/haproxy/haproxy.cfg
        line: "{{ lookup('template','/data/ansible/linux/5-ha-intranet/haproxy.cfg') }}" 
        insertafter: EOF
        state: present

    - name: Restart HAProxy
      ansible.builtin.service:
        name: haproxy
        state: restarted