---
- name: Configure Windows Environment
  hosts: windows
  gather_facts: false
  tasks:
    - name: Add Dependencies
      win_feature:
        name:
          - Web-Server
          - Web-Mgmt-Tools
        state: present

    - name: Configure as Domain Controller
      win_domain:
        dns_domain_name: customers.com
        safe_mode_password: P@ssw0rd
      register: domain_result

    - name: Set Domain Configuration Status
      set_fact:
        domain_configured: "{{ domain_result is defined and domain_result.changed }}"

    - name: Reboot if Domain Configuration Changed
      win_reboot:
      when: domain_configured
